<?php

$BUILDINGS = array(
'ACE'=>array('x'=>"4",'y'=>"5",'abbr'=>"ACE",'num'=>"522",'name'=>"Arts Computation Engineering Trailers",),
'ACT'=>array('x'=>"4",'y'=>"4",'abbr'=>"ACT",'num'=>"727",'name'=>"Art Culture & Technology",),
'ADM'=>array('x'=>"5",'y'=>"4",'abbr'=>"ADM",'num'=>"111",'name'=>"Administration",),
'AITR'=>array('x'=>"4",'y'=>"4",'abbr'=>"AITR",'num'=>"714",'name'=>"Arts Instruction & Technology Resource Center",),
'APL'=>array('x'=>"2",'y'=>"2",'abbr'=>"APL",'num'=>"94",'name'=>"Air Pollution Lab",),
'ARBO'=>array('x'=>"2",'y'=>"2",'abbr'=>"ARBO",'num'=>"96",'name'=>"Arboretum (North Campus)",),
'ARC'=>array('x'=>"10",'y'=>"4",'abbr'=>"ARC",'num'=>"680",'name'=>"Anteater Recreation Center",),
'ART'=>array('x'=>"4",'y'=>"4",'abbr'=>"ART",'num'=>"722",'name'=>"Art Studio",),
'BH'=>array('x'=>"6",'y'=>"6",'abbr'=>"BH",'num'=>"314",'name'=>"Computer Science III (Bren Hall)",),
'BLI'=>array('x'=>"3",'y'=>"7",'abbr'=>"BLI",'num'=>"817",'name'=>"Beckman Laser Institute",),
'BOAT'=>array('x'=>"0",'y'=>"0",'abbr'=>"BOAT",'num'=>"0",'name'=>"Boat House",),
'BP'=>array('x'=>"7",'y'=>"3",'abbr'=>"BP",'num'=>"4",'name'=>"Berkeley Place",),
'BRL'=>array('x'=>"4",'y'=>"5",'abbr'=>"BRL",'num'=>"512",'name'=>"Bonney Research Laboratory",),
'BSA'=>array('x'=>"4",'y'=>"6",'abbr'=>"BSA",'num'=>"515",'name'=>"Biological Sciences Administration",),
'CD'=>array('x'=>"1",'y'=>"3",'abbr'=>"CD",'num'=>"90",'name'=>"Child Development Center (North Campus)",),
'CH'=>array('x'=>"3",'y'=>"5",'abbr'=>"CH",'num'=>"903",'name'=>"Crawford Hall",),
'CNLM'=>array('x'=>"0",'y'=>"0",'abbr'=>"CNLM",'num'=>"0",'name'=>"Center for the Neurobiology of Learning & Memory",),
'QRL'=>array('x'=>"4",'y'=>"5",'abbr'=>"QRL",'num'=>"506",'name'=>"Qureshey Research Laboratory (CNLM)",),
'CRCC'=>array('x'=>"5",'y'=>"4",'abbr'=>"CRCC",'num'=>"103",'name'=>"Cross Cultural Center",),
'CRH'=>array('x'=>"5",'y'=>"6",'abbr'=>"CRH",'num'=>"417",'name'=>"Croul Hall",),
'CS'=>array('x'=>"6",'y'=>"5",'abbr'=>"CS",'num'=>"302",'name'=>"Information & Computer Science",),
'CSE'=>array('x'=>"6",'y'=>"6",'abbr'=>"CSE",'num'=>"312",'name'=>"Computer Science/Engineering",),
'CST'=>array('x'=>"0",'y'=>"0",'abbr'=>"CST",'num'=>"0",'name'=>"Computer Science Trailer",),
'CST2'=>array('x'=>"0",'y'=>"0",'abbr'=>"CST2",'num'=>"0",'name'=>"Computer Science Trailer 2",),
'CTT'=>array('x'=>"4",'y'=>"4",'abbr'=>"CTT",'num'=>"711",'name'=>"(Claire) Trevor Theatre",),
'CV'=>array('x'=>"4",'y'=>"6",'abbr'=>"CV",'num'=>"0",'name'=>"Campus Village",),
'DRA'=>array('x'=>"4",'y'=>"4",'abbr'=>"DRA",'num'=>"715",'name'=>"Drama Building",),
'DS'=>array('x'=>"4",'y'=>"4",'abbr'=>"DS",'num'=>"713",'name'=>"Dance Studio",),
'ECT'=>array('x'=>"6",'y'=>"5",'abbr'=>"ECT",'num'=>"317",'name'=>"Engineering & Computing Trailer",),
'EG'=>array('x'=>"6",'y'=>"6",'abbr'=>"EG",'num'=>"321",'name'=>"Engineering Gateway",),
'EIC'=>array('x'=>"0",'y'=>"0",'abbr'=>"EIC",'num'=>"0",'name'=>"Engineering Interim Classroom",),
'ELF'=>array('x'=>"7",'y'=>"5",'abbr'=>"ELF",'num'=>"323",'name'=>"Engineering Laboratory Facility",),
'ELH'=>array('x'=>"6",'y'=>"5",'abbr'=>"ELH",'num'=>"305",'name'=>"Engineering Lecture Hall",),
'ET'=>array('x'=>"6",'y'=>"5",'abbr'=>"ET",'num'=>"303",'name'=>"Engineering Tower",),
'FARMSCHOOL'=>array('x'=>"10",'y'=>"5",'abbr'=>"FARMSCHOOL",'num'=>"626",'name'=>"Farm School/Red Barn",),
'FRF'=>array('x'=>"2",'y'=>"2",'abbr'=>"FRF",'num'=>"95",'name'=>"Faculty Research Facility (North Campus)",),
'FRH'=>array('x'=>"5",'y'=>"6",'abbr'=>"FRH",'num'=>"401",'name'=>"(Frederick) Reines Hall",),
'GNRF'=>array('x'=>"3",'y'=>"7",'abbr'=>"GNRF",'num'=>"837",'name'=>"Gillespie Neuroscience Research Facility",),
'GSM'=>array('x'=>"7",'y'=>"4",'abbr'=>"GSM",'num'=>"221",'name'=>"Merage School of Business",),
'HH'=>array('x'=>"5",'y'=>"5",'abbr'=>"HH",'num'=>"601",'name'=>"Humanities Hall",),
'HIB'=>array('x'=>"4",'y'=>"4",'abbr'=>"HIB",'num'=>"610",'name'=>"Humanities Instructional Building",),
'HICF'=>array('x'=>"4",'y'=>"4",'abbr'=>"HICF",'num'=>"611",'name'=>"Humanities Interim Classroom Facility",),
'HOB2'=>array('x'=>"4",'y'=>"4",'abbr'=>"HOB2",'num'=>"625",'name'=>"Humanities Office Building 2",),
'HRH'=>array('x'=>"3",'y'=>"7",'abbr'=>"HRH",'num'=>"843",'name'=>"Hewitt Research Hall",),
'HSLH'=>array('x'=>"5",'y'=>"5",'abbr'=>"HSLH",'num'=>"501",'name'=>"(Howard) Schneiderman Lecture Hall",),
'HTC'=>array('x'=>"4",'y'=>"4",'abbr'=>"HTC",'num'=>"613",'name'=>"Humanities Trailer Complex",),
'ICF'=>array('x'=>"6",'y'=>"5",'abbr'=>"ICF",'num'=>"315",'name'=>"Interim Classroom Facility",),
'ICS'=>array('x'=>"6",'y'=>"5",'abbr'=>"ICS",'num'=>"302",'name'=>"Information & Computer Science",),
'ICS2'=>array('x'=>"6",'y'=>"6",'abbr'=>"ICS2",'num'=>"304",'name'=>"Information & Computer Science 2",),
'IH'=>array('x'=>"2",'y'=>"7",'abbr'=>"IH",'num'=>"835",'name'=>"Irvine Hall",),
'KH'=>array('x'=>"5",'y'=>"4",'abbr'=>"KH",'num'=>"600",'name'=>"Krieger Hall",),
'LLIB'=>array('x'=>"6",'y'=>"4",'abbr'=>"LLIB",'num'=>"102",'name'=>"Langson Library",),
'MAB'=>array('x'=>"3",'y'=>"4",'abbr'=>"MAB",'num'=>"58",'name'=>"Mesa Arts Building",),
'MDE'=>array('x'=>"6",'y'=>"5",'abbr'=>"MDE",'num'=>"311",'name'=>"McDonnell Douglas Engineering Auditorium",),
'MH'=>array('x'=>"5",'y'=>"5",'abbr'=>"MH",'num'=>"503",'name'=>"McGaugh Hall",),
'MM'=>array('x'=>"4",'y'=>"4",'abbr'=>"MM",'num'=>"726",'name'=>"Music & Media Building",),
'MPAA'=>array('x'=>"7",'y'=>"4",'abbr'=>"MPAA",'num'=>"3",'name'=>"Multipurpose Academic & Administrative Building",),
'MS1'=>array('x'=>"3",'y'=>"6",'abbr'=>"MS1",'num'=>"810",'name'=>"Medical Surge I",),
'MS2'=>array('x'=>"3",'y'=>"6",'abbr'=>"MS2",'num'=>"812",'name'=>"Medical Surge II",),
'MSB'=>array('x'=>"2",'y'=>"7",'abbr'=>"MSB",'num'=>"833",'name'=>"Medical Sciences Classroom Facility",),
'MSTB'=>array('x'=>"5",'y'=>"7",'abbr'=>"MSTB",'num'=>"415",'name'=>"Multipurpose Science & Technology Building",),
'NS1'=>array('x'=>"5",'y'=>"6",'abbr'=>"NS1",'num'=>"517",'name'=>"Natural Sciences 1",),
'PCB'=>array('x'=>"5",'y'=>"6",'abbr'=>"PCB",'num'=>"403",'name'=>"Parkview Classroom Building",),
'PH'=>array('x'=>"3",'y'=>"7",'abbr'=>"PH",'num'=>"829",'name'=>"Plumwood House",),
'PSCB'=>array('x'=>"5",'y'=>"6",'abbr'=>"PSCB",'num'=>"413",'name'=>"Physical Sciences Classroom Building",),
'PSLH'=>array('x'=>"5",'y'=>"6",'abbr'=>"PSLH",'num'=>"411",'name'=>"Physical Sciences Lecture Hall",),
'PSTU'=>array('x'=>"4",'y'=>"4",'abbr'=>"PSTU",'num'=>"728",'name'=>"Performance Studios",),
'REC'=>array('x'=>"6",'y'=>"5",'abbr'=>"REC",'num'=>"311",'name'=>"Rockwell Engineering Center",),
'RH'=>array('x'=>"5",'y'=>"6",'abbr'=>"RH",'num'=>"400",'name'=>"Rowland Hall",),
'SAIL'=>array('x'=>"0",'y'=>"0",'abbr'=>"SAIL",'num'=>"0",'name'=>"Sail Base",),
'SB'=>array('x'=>"6",'y'=>"4",'abbr'=>"SB",'num'=>"221",'name'=>"Merage School of Business",),
'SC CCA'=>array('x'=>"5",'y'=>"4",'abbr'=>"SC CCA",'num'=>"113",'name'=>"UCI Student Center Crystal Cove Auditorium",),
'SCS'=>array('x'=>"4",'y'=>"4",'abbr'=>"SCS",'num'=>"720",'name'=>"Sculpture and Ceramic Studios",),
'SE'=>array('x'=>"6",'y'=>"4",'abbr'=>"SE",'num'=>"210",'name'=>"Social Ecology I",),
'SE2'=>array('x'=>"6",'y'=>"4",'abbr'=>"SE2",'num'=>"215",'name'=>"Social Ecology II",),
'SH'=>array('x'=>"4",'y'=>"5",'abbr'=>"SH",'num'=>"502",'name'=>"Steinhaus Hall",),
'SLIB'=>array('x'=>"4",'y'=>"6",'abbr'=>"SLIB",'num'=>"520",'name'=>"Science Library",),
'SPH'=>array('x'=>"3",'y'=>"7",'abbr'=>"SPH",'num'=>"839",'name'=>"Sprague Hall",),
'SS2'=>array('x'=>"5",'y'=>"4",'abbr'=>"SS2",'num'=>"105",'name'=>"Student Services II",),
'SSH'=>array('x'=>"6",'y'=>"4",'abbr'=>"SSH",'num'=>"200",'name'=>"Social Science Hall",),
'SSL'=>array('x'=>"6",'y'=>"5",'abbr'=>"SSL",'num'=>"202",'name'=>"Social Science Laboratory",),
'SSLH'=>array('x'=>"6",'y'=>"4",'abbr'=>"SSLH",'num'=>"212",'name'=>"Social Science Lecture Hall",),
'SSPA'=>array('x'=>"6",'y'=>"4",'abbr'=>"SSPA",'num'=>"211",'name'=>"Social Science Plaza A",),
'SSPB'=>array('x'=>"6",'y'=>"4",'abbr'=>"SSPB",'num'=>"213",'name'=>"Social Science Plaza B",),
'SST'=>array('x'=>"6",'y'=>"4",'abbr'=>"SST",'num'=>"201",'name'=>"Social Science Tower",),
'SSTR'=>array('x'=>"6",'y'=>"4",'abbr'=>"SSTR",'num'=>"203",'name'=>"Social Science Trailer",),
'STU4'=>array('x'=>"4",'y'=>"4",'abbr'=>"STU4",'num'=>"725",'name'=>"Studio Four",),
'TBA'=>array('x'=>"0",'y'=>"0",'abbr'=>"TBA",'num'=>"0",'name'=>"To be arranged",),
'UCI BARN'=>array('x'=>"10",'y'=>"5",'abbr'=>"UCI BARN",'num'=>"626",'name'=>"Farm School/Red Barn",),
'UCI MC'=>array('x'=>"20",'y'=>"20",'abbr'=>"UCI MC",'num'=>"0",'name'=>"UCI Medical Center",),
'UNEXA'=>array('x'=>"7",'y'=>"4",'abbr'=>"UNEXA",'num'=>"231",'name'=>"University Extension A",),
'WSH'=>array('x'=>"4",'y'=>"4",'abbr'=>"WSH",'num'=>"710",'name'=>"(Winifred) Smith Hall",),
);


global $BUILDINGS;

?>